version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vitalapp
    ports:
      - "5432:5432"
  web:
    image: smdussan/practicadevops-web
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
